### ISSUE TITLE
"Nothing to be done"

### ISSUE THREAD

**Issue by jessiechan0752** [zhxiaokang/RASflow#11]
Hi,

Thank you for the nice pipeline development.

I first tried QC for the fastq samples without further downstream application. And the feedback from the pipeline is:

```
main.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(yamlfile)
Is quality control required?
 True
Is trimming required?
 False
Which mapping reference will be used?
 genome
Is DEA required?
 False
Is visualization required?
 False
Please double check the information above
Do you want to continue? (y/n)
y
Start RASflow on project: calderon_et_al
Are you sure that you want to do Quality Control?
 If yes, type 'y'; if not, type 'n' and set 'QC' to 'no' in the config file
y
Start Quality Control!
Building DAG of jobs...
Nothing to be done.
Complete log: /home/RASflow/.snakemake/log/2020-06-08T212542.413870.snakemake.log
Quality control is done!
 Please check the report and decide whether trimming is needed
 Please remember to turn off the QC in the config file!
```

And I found nothing in my pre-defined output directory.

Can you help sort out the issue?

Many thanks!

Jessie

**Comment by zhxiaokang** [comment]
Hi Jessie,

Thank you for using RASflow. 

Snakemake will always check the final "output" (the input of rule end) and if it finds that the required file is already there, it will do nothing but just say "Nothing to be done." 

And the final "output" of QC is: `config["FINALOUTPUT"] + "/" + config["PROJECT"]+ "/fastqc/report_quality_control.html"` (this can be found in [workflow/quality_control.rules](https://github.com/zhxiaokang/RASflow/blob/master/workflow/quality_control.rules)), and the first two paras are defined in the config file `configs/config_main.yaml`. So I suggest to check whether that file is already there (even an empty file with that name) and delete it if it exists. And rerun the workflow.

**Comment by jessiechan0752** [comment]
Thank you for the detail explanation Xiaokang! This issue is solved, but now I have another question: can we start the pipeline directly from DEA without alignment?

**Comment by zhxiaokang** [comment]
Yes, but it's tricky. Because you need to make sure that the quantification of transcript/gene is already done and the files are organized in a way that RASflow can recognize (refer to the output from `quantify_trans.rules` if transcriptome is used as ref, or `align_count_genome.rules` if genome is used as ref. Then you can use the Snakemake file for DEA:
`nice -5 snakemake -s workflow/dea_trans.rules 2>&1 | tee logs/log_dea_trans.txt` if you're using transcriptome as reference, or
`nice -5 snakemake -s workflow/dea_genome.rules 2>&1 | tee logs/log_dea_genome.txt` if the genome is used as reference.

**Comment by jessiechan0752** [comment]
Problem solved! Thanks a lot Xiaokang!

**Comment by zhxiaokang** [comment]
Glad to hear that. I'll then close this issue. Feel free to open a new issue when you have another problem.
