### ISSUE TITLE
Where to get genome and annotation files

### ISSUE THREAD

**Issue by smartgamer** [zhxiaokang/RASflow#15]
Hi,

I'm trying to use the RASflow and want to use the complete genome and annotation files(human). I tried to download files from https://uswest.ensembl.org/info/data/ftp/index.html, but don't know which files to download and fill the section for "Configuration for alignment to genome and feature count " in config_main.yaml. 
The original setting in the config_main.yaml is: 

## genome and annotation files
GENOME: data/example/ref/genome/Homo_sapiens.GRCh38.dna.chromosome.1.1.10M.fa
ANNOTATION: data/example/ref/annotation/Homo_sapiens.GRCh38.93.1.1.10M.gtf

I want to replace these files with complete human genome files. Where can I download them and which files?

Thanks,

**Comment by kalavattam** [comment]
These links ought do the trick.

```
# GENOME
ftp://ftp.ensembl.org/pub/release-101/fasta/homo_sapiens/dna/

# ANNOTATION
ftp://ftp.ensembl.org/pub/release-101/gtf/homo_sapiens
```

**Comment by smartgamer** [comment]
Thank you so much

Charles

On Oct 25, 2020, at 10:54 PM, Kris Alavattam <notifications@github.com> wrote:

﻿

These links ought to do the trick.

# GENOME
ftp://ftp.ensembl.org/pub/release-101/fasta/homo_sapiens/dna/

# ANNOTATION
ftp://ftp.ensembl.org/pub/release-101/gtf/homo_sapiens

**Comment by zhxiaokang** [comment]
Thank you @kalavattam
