### ISSUE TITLE
Problems Nanopore Align 

### ISSUE THREAD

**Issue by AGaliana** [zhxiaokang/RASflow#17]
Hi!

 I'm trying to use RASFlow for first time with ONT Minion (with master branch), after align step with HISAT2 no reads are aligned. I also tried bwa branch but there are some tokens errors so the pipeline fails (im using macOs Catalina). Any suggestion? maybe there are some hisat2 configuration for Nanopore??

Thank you in advance

AG

Alignment ressults:
38280 reads; of these:
  38280 (100.00%) were unpaired; of these:
    38280 (100.00%) aligned 0 times
    0 (0.00%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
0.00% overall alignment rate

**Comment by zhxiaokang** [comment]
It seems that HISAT2 is not proper for long reads alignment, as this paper [Evaluation of tools for long read RNA-seq splice-aware alignment ](https://www.biorxiv.org/content/10.1101/126656v1.full.pdf) has a similar finding as you.
