### ISSUE TITLE
Issue with environment creation on macOS Big Sur

### ISSUE THREAD

**Issue by Yogurin88** [zhxiaokang/RASflow#22]
Hi, when I try to create the rasflow environment with the given command "conda env create -n rasflow -f env.yaml" it gets stuck in the resolving environment step. I have successfully installed and used rasflow in Ubuntu LTS 20.4 and in a WSL vm with the same OS but can't really install it on my work computer. Is there any workaround?

Thanks in advance.

**Comment by zhxiaokang** [comment]
Hi, this issue has also been reported by some other users. As you have experienced, everything works fine on Linux, but not on Mac. The guess is that some tools for Mac are out of date, so if you remove the version specifications from `env.yaml`, then the environment can be set up smoothly on Mac. But then all the tools installed are at the latest version. Some tools have been changed so much compared with the versions specified in the current `env.yaml`, that they are not compatible with the current RASflow.

One feasible solution is to update RASflow to make it compatible with the latest tools (fix the reported errors one by one), but I don't have enough time for that right now. So, unfortunately, I don't have a good solution to the issue with Mac...

If you're interested in and have time for this, it would be great if you could try the solution I mentioned above and fix the new-version conflict with RASflow on Mac.

**Comment by zhxiaokang** [comment]
Hi @Yogurin88 I finally found some time to get this issue fixed. Please refer to the new [Tutorial](https://github.com/zhxiaokang/RASflow/blob/master/Tutorial.pdf) where I've added the Docker solution for Mac. I've tested on the test data (mapping to transcriptome). Hope it runs well on your dataset, otherwise, you're more than welcome to report the bug you may discover.
