### ISSUE TITLE
Gtf file format error

### ISSUE THREAD

**Issue by yashsondhi** [zhxiaokang/RASflow#26]
Hi Zhang, 
I am having issues with the gtf file format, I assume this is something I could fix by changing the index? I have attached the output of the cluster run, but I am not sure where I should edit this parameter?

ERROR: failed to find the gene identifier attribute in the 9th column of the provided GTF file.
The specified gene identifier attribute is 'gene_id' 
An example of attributes included in your GTF annotation is 'transcript_id "evm.model.chr1.34";' 
The program has to terminate. 

First few lines of the gtf file

GWHABGR00000001	EVM	transcript	15372	30018	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1"
GWHABGR00000001	EVM	exon	15372	15520	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	16212	16351	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	17501	17758	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	18192	18405	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	18529	18690	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	20641	20838	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	22769	22861	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1";
GWHABGR00000001	EVM	exon	23546	23685	.	-	.	transcript_id "evm.model.chr1.1"; gene_id "evm.TU.chr1.1"
[serial_test_9441360.log](https://github.com/zhxiaokang/RASflow/files/7259207/serial_test_9441360.log)
;

**Comment by zhxiaokang** [comment]
Hi, as the error message explains, featureCounts expects the 9th field to be "gene_id" but in your gtf file it's "transcript_id". Since you're counting genes, so I suggest to simply remove the transcript part. So the following command should do the job:
```
cut -d" " -f1-8,11-12 old.gtf > new.gtf
```

**Comment by yashsondhi** [comment]
Hi,
Thanks for the prompt response.
I tried to go through feature counters documentation, I wasn't sure sure I
should modify the gtf file.
Cheers
