### ISSUE TITLE
Multiple comparison with 2 treatments

### ISSUE THREAD

**Issue by dmontielg** [zhxiaokang/RASflow#27]
Hi,

I was wondering wether the workflow can handle multiple comparisons.
[https://github.com/zhxiaokang/RASflow/blob/master/configs/metadata.tsv]
I have three groups: 
   - 1. Control 
   - 2. Treatment_A 
   - 3. Treatment_B
In the metadata table I see this only works with a control group and one treatment comparison group at a time or should I run another workflow with my other treatment and the control?

Thanks in advanced

**Comment by zhxiaokang** [comment]
Hi, RASflow only allows a test/comparison between two groups, but in one run, you can define several tests. You can define those comparisons in `configs/config_main.yaml` in the following block:
```
## the comparison(s) you want to do. If multiple comparisons, specify each pair (CONTROL & TREAT) in order respectively
CONTROL: ["Control", "Control"]
TREAT: ["Treatment_A", "Treatment_B"]
## length of 'CONTROL' should agree with that of 'TREAT'
## what you fill in there should agree with the "group" column in metadata.tsv
```
which asks RASflow to run 2 comparisons: `Control` vs. `Treatment_A` and `Control` vs. `Treatment_B`

**Comment by dmontielg** [comment]
Thanks a lot for your response!
