### ISSUE TITLE
DEA error

### ISSUE THREAD

**Issue by BobW4ng** [zhxiaokang/RASflow#30]
Hello Mr.Zhang,
For some reason, I am getting an error in the DEA steps.
Error in tximport(files, type = "salmon", txOut = TRUE, countsFromAbundance = "no") :
  all(file.exists(files)) is not TRUE
Calls: DEA -> tximport -> stopifnot
Execution halted
[Mon Sep 12 11:16:57 2022]
Error in rule DEA:
    jobid: 1
    output: output/WT/trans/dea/DEA/transcript-level/dea_wt_ko.tsv, output/WT/trans/dea/DEA/transcript-level/deg_wt_ko.tsv, output/WT/trans/dea/DEA/gene-level/dea_wt_ko.tsv, output/WT/trans/dea/DEA/gene-level/deg_wt_ko.tsv

RuleException:
CalledProcessError in line 40 of /mnt/d/RNAseq/qhd2/workflow/dea_trans.rules:
Command ' set -euo pipefail;  Rscript scripts/dea_trans.R ' returned non-zero exit status 1.
  File "/mnt/d/RNAseq/qhd2/workflow/dea_trans.rules", line 40, in __rule_DEA
  File "/home/wbc/miniconda3/envs/ranseqSnakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/d/RNAseq/qhd2/.snakemake/log/2022-09-12T110512.827029.snakemake.log
DEA is done!
Visualization is not required and RASflow is done!
Building DAG of jobs...
Nothing to be done.
Complete log: /mnt/d/RNAseq/qhd2/.snakemake/log/2022-09-12T110510.915007.snakemake.log

Any help is appreciated. Thank you.

**Comment by zhxiaokang** [comment]
As I can understand from the error message, 
```
Error in tximport(files, type = "salmon", txOut = TRUE, countsFromAbundance = "no") :
all(file.exists(files)) is not TRUE
```
it seems that the quantity files (output from `salmon`) are not there, please check whether you have `output/WT/trans/quant/[sample]/quant.sf`

**Comment by BobW4ng** [comment]
thank you sir！

**Comment by zhxiaokang** [comment]
No problem. I will then close it. Feel free to reopen it if the same error remains there. And also feel free to open new issues if some new error occurs.
