### ISSUE TITLE
Can't run the examples

### ISSUE THREAD

**Issue by antoniaprn** [zhxiaokang/RASflow#34]
Hi, thank you for your work. I'm just installed RASflow by the Conda environment with the yaml file env.yaml like the tutorial and tried to run the example changing the project name and even another sample, but keeping get the error in the first QC to stop that is `nice: ‘snakemake’: No such file or directory` and the outputs files don't appear. 

This is how is my config_main.yaml characteristics was:

PROJECT: teste
QC: yes  # "yes" or "no"
TRIMMED: no  # "yes" or "no"?
REFERENCE: genome  # "genome" or "transcriptome"
DEA: yes  # "yes" or "no"
VISUALIZE: no  # "yes" or "no"
READSPATH: data/example/fastq_pair
METAFILE: configs/metadata.tsv
END: pair 
NCORE: 40 
OUTPUTPATH: data/output/teste # intermediate output. do not upload to github
FINALOUTPUT: output/teste
GENOME: data/example/ref/genome/Homo_sapiens.GRCh38.dna.chromosome.1.1.10M.fa
ANNOTATION: data/example/ref/annotation/Homo_sapiens.GRCh38.93.1.1.10M.gtf
ALIGNER: hisat2
COUNTER: featureCounts  
alignmentQC: no  # "yes" or "no" to specify whether you want to do alignment QC
DEATOOL: DESeq2  
PAIR: FALSE  # Is this a pair test or not? ("TRUE" or "FALSE")
CONTROL: ["Untreated"]
TREAT: ["Dexamethasone"]
 obs.: a let false just for testing if goes.

FILTER:
  yesOrNo: FALSE  # Filter out low expressed transcripts/genes or not? (TRUE or FALSE) It's better to be set to TRUE. FALSE is set as default only for testing fake toy data

**Comment by zhxiaokang** [comment]
Hi, I suppose that you have created the environment successfully, then `snakemake` should be there. The reason of this error could be that you are not in that environment.

To active the environment, use command `conda activate rasflow` (if you named the environment as 'rasflow'). The detailed explanation is on Page 3 of the [Tutorial](https://github.com/zhxiaokang/RASflow/blob/master/Tutorial.pdf)

**Comment by antoniaprn** [comment]
Yes, but I am in the environment that's why I can find out the problem.

**Comment by zhxiaokang** [comment]
Try `conda list` (Conda Doc [here](https://docs.conda.io/projects/conda/en/latest/commands/list.html) ) to check whether `snakemake` is there. If not, I suspect that the environment was not successfully created. Then either try creating the Conda environment again, or try using Docker
