### ISSUE TITLE
process was be killed, ram is not enough.

### ISSUE THREAD

**Issue by Youglas** [zhxiaokang/RASflow#38]
hi@zhxiaokang,
please help, my ram is not enough, what solutions for this problem . 8g ram only,  so bad, hopefully i own a new powerful notebook,...
sincerely,
luoying

**Comment by zhxiaokang** [comment]
Hi Luoying,

No worries, RASflow already takes care of small-ram machines. Actually, it's only alignment to genome that takes up a lot RAM, so you can simply map your reads to transcriptome instead of genome. 

Set "REFERENCE" to "transcriptome" in the config file, and also specify the transcriptome file there.

**Comment by Youglas** [comment]
Hi zhxiaokang,
Thank u for replying. So what is the next step? I find "## Which mapping reference do you want to use? Genome or transcriptome?
REFERENCE: transcriptome  # "genome" or "transcriptome" in config_main.yaml, i don't know how to solve the config problem, that means i can't use RASflow for no environment. 
sincerely,
Luo
"

**Comment by Youglas** [comment]
> Hi Luoying,
> 
> No worries, RASflow already takes care of small-ram machines. Actually, it's only alignment to genome that takes up a lot RAM, so you can simply map your reads to transcriptome instead of genome.
> 
> Set "REFERENCE" to "transcriptome" in the config file, and also specify the transcriptome file there.

so this is output, 
```youglas@youglas:~/RASflow$ conda env create -n rasflow -f env.yaml
Collecting package metadata (repodata.json): done
Solving environment: / Killed
```
Can u give me some advice, please.
sincerely,
Luo

**Comment by zhxiaokang** [comment]
The error message seems to come from the environment setup. I suggest you follow the instructions in this [Tutorial](https://github.com/zhxiaokang/RASflow/blob/master/Tutorial.pdf). Over there you'll find how to set up the environment properly, and how to config the workflow to run the transcriptome mapping pipeline.

**Comment by Youglas** [comment]
> The error message seems to come from the environment setup. I suggest you follow the instructions in this [Tutorial](https://github.com/zhxiaokang/RASflow/blob/master/Tutorial.pdf). Over there you'll find how to set up the environment properly, and how to config the workflow to run the transcriptome mapping pipeline.

**Comment by Youglas** [comment]
> The error message seems to come from the environment setup. I suggest you follow the instructions in this [Tutorial](https://github.com/zhxiaokang/RASflow/blob/master/Tutorial.pdf). Over there you'll find how to set up the environment properly, and how to config the workflow to run the transcriptome mapping pipeline.

I just follow the step and codes (the 2.1 For Linux), every step is on the tuto.
 After using ```conda env create -n rasflow -f env.yaml``` of the tutorial, ram was increasing fastly, then terminal show ```Collecting package metadata (repodata.json): done
Solving environment: - Killed```
I guess if some way can divide "env.yaml" to some small part, in order to solve the "killed".

**Comment by zhxiaokang** [comment]
Aha, then it seems that you really need a new notebook with larger RAM :-)

But before that, I found this post that you may try out if it helps: [stackoverflow post](https://stackoverflow.com/a/67454782/6255138) (the answer from _ning_)
```
sudo fallocate -l 1G /swapfile 
sudo chmod 600 /swapfile 
sudo mkswap /swapfile 
sudo swapon /swapfile 
sudo cp /etc/fstab /etc/fstab.bak 
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
```
