### ISSUE TITLE
Quantification after trimming

### ISSUE THREAD

**Issue by vinh-tr** [zhxiaokang/RASflow#5]
In quantify_trans_rules,
 I think that input_path is misspecified if there is a trimming step in the pipeline:

if trimmed:
    input_path = config["OUTPUTPATH"] + "/" + config["PROJECT"] + "/trim"

instead of :
if trimmed:
   input_path = config["OUTPUTPATH"] + "/trim"

Best regards,

**Comment by zhxiaokang** [comment]
Thank you, well spotted! It's now fixed.
