### ISSUE TITLE
Running on a cluster

### ISSUE THREAD

**Issue by yashondhi** [zhxiaokang/RASflow#6]
Hi,
I want to run it on a cluster using a bash script, is there some way to silence the checkpoints once the trimming is done. It cannot be run non-interactively.

**Comment by zhxiaokang** [comment]
Hi, if that comes from the workflow, simply modify main.py (it's a simple python code and easy to read); if that comes from the command of trimming itself, then you need to check out the manual of [Trim Galore](https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/), and maybe add some flag to the trimming command (the rule "trim" in file workflow/trim.rules)

**Comment by yashondhi** [comment]
Hi
Thanks, just wanted to make sure.
Cheers
Yash

**Comment by zhxiaokang** [comment]
Hi, great! I'll close the issue for now. Don't hesitate to reopen it or open another one if you have other questions.
